### PR TITLE
Fix dot product

### PR DESCRIPTION
**Pull request by petercollingridge**
Took me a while, but I finally tracked down the issue. My debugging technique involves putting a load of `console.log` everywhere and making sure I get what I expect.

It might be worth looking into unit testing so you can make sure all your functions are working as you expect.

### CODE REVIEW

**Comment by petercollingridge** [comment]
This is an example of some unit tests. You don't have to use it. The idea is that as you add code you add tests. Simply the act of writing tests often helps you find errors. Then whenever you update your code, you run the tests (by viewing the `tests.html` page) and so be a little bit more confident your changes haven't broken anything. It's definitely worth knowing about if you ever want to code professionally.

**Comment by petercollingridge** [comment]
These tests are using QUnit (https://api.qunitjs.com/) which is pretty easy to get started with, but there are loads of other systems/libraries out there.

**Comment by naclcaleb** [comment]
Oh, wow. Now if I had just used a standard vector math library...

I know. I probably should use unit tests. I've just never felt like I've needed them.

Sounds like you and I have a similar debugging process though 😆

**Comment by petercollingridge** [comment]
I think it's good to write your own vector math library. You probably don't really need unit test, it's just a good thing to know about. They are quite fun to write and watch them pass, at least to start with, though I do tend to get bored after a while and give up.

**Comment by naclcaleb** [comment]
Yea, it probably doesn't matter much here.

I probably should be using them in my "production" projects though...I'm too lazy I guess. I like the _idea_ of having automatic unit tests, but in practice...☺️

**Comment by naclcaleb** [comment]
There must be a problem still, because the lighting looks even less consistent now...

**Pull request merged**
